@TestOn('browser')
library test.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/ -e Environment.browser --no-genHtml`

import 'package:test/test.dart';
import './identity_controller_test.dart' as identity_controller_test;
import './register_test.dart' as register_test;
import './user_controller_test.dart' as user_controller_test;

void main() {
  identity_controller_test.main();
  register_test.main();
  user_controller_test.main();
}
