language: dart
sudo: required
addons:
  postgresql: "11"
services:
  - postgresql
before_script:
  - docker-compose up -d
  - pub get
script: pub run test -j 1 -r expanded
after_script:
  - docker-compose down
branches:
  only:
    - master
